# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/graph',
                'doc_host': 'https://DiTscho.github.io',
                'git_url': 'https://github.com/DiTscho/graph',
                'lib_path': 'graph'},
  'syms': {'graph.core': {'graph.core.foo': ('core.html#foo', 'graph/core.py')}}}
